### ISSUE TITLE
Bad "heading" in search results

### ISSUE THREAD

**Issue by dittaeva** [Plantemangfald/plantemangfald.no#29]
See second item in listing in attachment
![Screenshot from 2022-03-29 15-44-44](https://user-images.githubusercontent.com/397265/160625912-94134d09-9574-435c-a3c0-367270e59050.png)
.

**Comment by beatricebieuville** [comment]
This is very bad indeed. Though there was a `<title>` tag on each page. After researching it a little, it seems that Google is ken on ignoring tags if they are not good enough or repeating on the webpage. The next thing it will take as info is alt text from the main picture (in the present case, the logo – I do not know how Google established that it is the main picture).  

### Title

Anyways, I tried something to have a ≠ title on each page. Here is my pre-rendering html now:

`<title>{{ if .IsHome }}Plantemangfald: heim{{ else }}{{ if .Params.Title }}{{ .Params.Title }}{{else if .Site.Params.Title}}{{ .Site.Params.Title }}{{ else }}Plantemangfald{{ end }}{{ end }}</title>`

Which is quite self-explaining when you read it. `{{ .Params.Title }}` will pull data from the .md file (this is the case for the about page), but if it does not find this info, it will first try to get this info from the website's config file, and if not still, it will use "Plantemangfald". 

Exception is made for the homepage, which has "Plantemangfald: heim".

### Description

I also added description following a similar logic:

`<meta name="description" content="{{ if .Params.Description }}{{ trim .Params.Description "\n" }}{{else if .Site.Params.Description}}{{ trim .Site.Params.Description "\n"}}{{ end }}"/>`
